import { Client, Employee, Service, ServiceOrder, Transaction, User } from "../types";

export const MOCK_USER: User = {
  id: "user-1",
  name: "Lorena Queiroz",
  email: "lorena@festaseventos.com.br",
  role: "admin",
  avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
};

export const MOCK_CLIENTS: Client[] = [
  {
    id: "cli-1",
    nome: "Carlos Eduardo da Silva",
    email: "carlos.edu@gmail.com",
    telefone: "(11) 98765-4321",
    documento: "123.456.789-00",
    endereco: "Av. Paulista, 1000, Apt 14 - Bela Vista, São Paulo - SP",
    observacoes: "Cliente premium. Prefere atendimento nos fins de semana.",
    createdAt: "2026-01-15T10:00:00.000Z",
  },
  {
    id: "cli-2",
    nome: "Mariana Alencar Costa",
    email: "mariana.costa@empresa.com.br",
    telefone: "(11) 99888-7766",
    documento: "45.678.901/0001-23",
    endereco: "Rua das Figueiras, 450 - Jardim, Santo André - SP",
    observacoes: "Empresa de tecnologia. Eventos corporativos frequentes.",
    createdAt: "2026-02-10T14:30:00.000Z",
  },
  {
    id: "cli-3",
    nome: "Roberto Mendes Junior",
    email: "roberto.mendes@yahoo.com.br",
    telefone: "(21) 97777-6655",
    documento: "987.654.321-11",
    endereco: "Av. Atlântica, 2200 - Copacabana, Rio de Janeiro - RJ",
    observacoes: "Festa de aniversário de 50 anos planejada.",
    createdAt: "2026-03-01T09:15:00.000Z",
  },
  {
    id: "cli-4",
    nome: "Juliana Frota Marques",
    email: "juliana.frota@outlook.com",
    telefone: "(31) 96543-2109",
    documento: "234.567.890-12",
    endereco: "Rua Sergipe, 120 - Savassi, Belo Horizonte - MG",
    observacoes: "Festa de casamento intimista (Mini Wedding).",
    createdAt: "2026-03-12T16:45:00.000Z",
  },
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: "emp-1",
    nome: "Rodrigo Vasconcelos",
    cargo: "Bartender Principal",
    telefone: "(11) 91111-2222",
    valorDiaria: 250.0,
    tipoPagamento: "diaria",
    observacoes: "Especialista em coquetéis moleculares e shows pirotécnicos.",
    createdAt: "2026-01-02T08:00:00.000Z",
  },
  {
    id: "emp-2",
    nome: "Ana Carolina Santos",
    cargo: "Decoradora e Florista",
    telefone: "(11) 92222-3333",
    valorDiaria: 350.0,
    tipoPagamento: "diaria",
    observacoes: "Responsável pelo design floral e arranjos suspensos.",
    createdAt: "2026-01-05T09:00:00.000Z",
  },
  {
    id: "emp-3",
    nome: "Daniel Souza Lima",
    cargo: "DJ e Técnico de Som",
    telefone: "(11) 93333-4444",
    valorDiaria: 400.0,
    tipoPagamento: "diaria",
    observacoes: "Possui equipamento próprio de som de alta performance.",
    createdAt: "2026-01-10T11:00:00.000Z",
  },
  {
    id: "emp-4",
    nome: "Gabriela Martins Rocha",
    cargo: "Chefe de Cozinha / Buffet",
    telefone: "(11) 94444-5555",
    valorDiaria: 500.0,
    tipoPagamento: "diaria",
    observacoes: "Culinária fina contemporânea. Elabora cardápios personalizados.",
    createdAt: "2026-01-20T10:00:00.000Z",
  },
  {
    id: "emp-5",
    nome: "Marcos Antonio Mendes",
    cargo: "Garçom Líder",
    telefone: "(11) 95555-6666",
    valorDiaria: 180.0,
    tipoPagamento: "diaria",
    observacoes: "Excelente comunicação. Coordena a equipe de apoio de salão.",
    createdAt: "2026-02-01T08:30:00.000Z",
  },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: "srv-1",
    nome: "Serviço de Garçons (Equipe c/ 3)",
    descricao: "Equipe com 3 garçons treinados e uniformizados para atendimento volante de buffet e bebidas.",
    valor: 540.0,
    duracaoHoras: 6,
    categoria: "Serviço de Apoio",
    status: "ativo",
  },
  {
    id: "srv-2",
    nome: "Decoração Temática Completa",
    descricao: "Arranjos florais premium, painel decorativo, mobiliário rústico ou moderno e iluminação cênica de mesa.",
    valor: 3500.0,
    duracaoHoras: 12,
    categoria: "Decoração",
    status: "ativo",
  },
  {
    id: "srv-3",
    nome: "Sonorização & DJ de Alta Performance",
    descricao: "DJ profissional, pickup, 2 caixas ativas de 1000W, microfones sem fio e mesa de som de 12 canais.",
    valor: 1200.0,
    duracaoHoras: 8,
    categoria: "Som & Iluminação",
    status: "ativo",
  },
  {
    id: "srv-4",
    nome: "Iluminação de Pista de Dança (Grid)",
    descricao: "Estrutura box truss em formato 'trave' ou 'X' com 4 moving heads, estrobo, fumaça e efeitos de laser.",
    valor: 1800.0,
    duracaoHoras: 8,
    categoria: "Som & Iluminação",
    status: "ativo",
  },
  {
    id: "srv-5",
    nome: "Open Bar de Coquetéis (Bartenders)",
    descricao: "Estrutura física de bar iluminado, bartenders e insumos inclusos para 5 tipos de coquetéis premium com e sem álcool.",
    valor: 2500.0,
    duracaoHoras: 6,
    categoria: "Bebidas & Bar",
    status: "ativo",
  },
  {
    id: "srv-6",
    nome: "Buffet Completo Finger Food (P/ 50 pessoas)",
    descricao: "Cardápio variado de canapés quentes e frios, mini risotos, mini hambúrgueres artesanais e sobremesas finas.",
    valor: 4500.0,
    duracaoHoras: 5,
    categoria: "Gastronomia",
    status: "ativo",
  },
  {
    id: "srv-7",
    nome: "Equipe de Segurança & Recepção (2 profissionais)",
    descricao: "Segurança de portaria e recepcionista/controlador de acesso com lista digital/QR Code.",
    valor: 800.0,
    duracaoHoras: 7,
    categoria: "Segurança",
    status: "ativo",
  },
];

export const MOCK_ORDERS: ServiceOrder[] = [
  {
    id: "os-1",
    codigo: "OS-2026-0001",
    clienteId: "cli-1",
    dataEvento: "2026-05-15",
    horarioInicio: "18:00",
    horarioFim: "23:59",
    local: "Espaço Jardins - Av. Europa, 1200, São Paulo - SP",
    status: "confirmado",
    formaPagamento: "Pix (50% entrada + 50% no dia)",
    observacoes: "Festa infantil de luxo. Necessário montagem e passagem de som até as 15:00.",
    itens: [
      { serviceId: "srv-2", quantidade: 1, valorUnitario: 3500.0 },
      { serviceId: "srv-3", quantidade: 1, valorUnitario: 1200.0 },
      { serviceId: "srv-1", quantidade: 1, valorUnitario: 540.0 },
    ],
    funcionariosIds: ["emp-2", "emp-3", "emp-5"],
    assinaturaNome: "Carlos Eduardo da Silva",
    assinaturaData: "2026-01-20T11:30:00.000Z",
    anexos: [
      "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=600&q=80"
    ],
    valorTotal: 5240.0,
    createdAt: "2026-01-20T11:00:00.000Z",
  },
  {
    id: "os-2",
    codigo: "OS-2026-0002",
    clienteId: "cli-2",
    dataEvento: "2026-05-22",
    horarioInicio: "14:00",
    horarioFim: "22:00",
    local: "Espaço Rooftop Faria Lima - Av. Brig. Faria Lima, 3477, São Paulo - SP",
    status: "em_andamento",
    formaPagamento: "Faturamento 30 dias após evento",
    observacoes: "Evento corporativo de encerramento de trimestre. Painéis de LED já contratados por fora.",
    itens: [
      { serviceId: "srv-5", quantidade: 1, valorUnitario: 2500.0 },
      { serviceId: "srv-6", quantidade: 1, valorUnitario: 4500.0 },
      { serviceId: "srv-7", quantidade: 1, valorUnitario: 800.0 },
      { serviceId: "srv-1", quantidade: 2, valorUnitario: 540.0 }, // 2 equipes
    ],
    funcionariosIds: ["emp-1", "emp-4", "emp-5"],
    assinaturaNome: "Mariana Alencar Costa",
    assinaturaData: "2026-02-15T15:20:00.000Z",
    anexos: [
      "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=600&q=80"
    ],
    valorTotal: 8880.0,
    createdAt: "2026-02-15T15:00:00.000Z",
  },
  {
    id: "os-3",
    codigo: "OS-2026-0003",
    clienteId: "cli-3",
    dataEvento: "2026-06-05",
    horarioInicio: "21:00",
    horarioFim: "05:00",
    local: "Clube Hípico do Rio de Janeiro - Lagoa, Rio de Janeiro - RJ",
    status: "pendente",
    formaPagamento: "Cartão de Crédito em 3x sem juros",
    observacoes: "Festa de aniversário temática estilo anos 80. Muita iluminação neon solicitada.",
    itens: [
      { serviceId: "srv-3", quantidade: 1, valorUnitario: 1200.0 },
      { serviceId: "srv-4", quantidade: 1, valorUnitario: 1800.0 },
      { serviceId: "srv-5", quantidade: 1, valorUnitario: 2500.0 },
    ],
    funcionariosIds: ["emp-3", "emp-1"],
    assinaturaNome: "",
    assinaturaData: "",
    anexos: [],
    valorTotal: 5500.0,
    createdAt: "2026-03-02T10:00:00.000Z",
  },
  {
    id: "os-4",
    codigo: "OS-2026-0004",
    clienteId: "cli-4",
    dataEvento: "2026-05-10",
    horarioInicio: "12:00",
    horarioFim: "18:00",
    local: "Sítio Primavera - Lagoa Santa - MG",
    status: "finalizado",
    formaPagamento: "Pix Integral à Vista com 5% desc.",
    observacoes: "Mini wedding ao ar livre. Clima propenso a chuva, necessário tenda (não inclusa).",
    itens: [
      { serviceId: "srv-2", quantidade: 1, valorUnitario: 3500.0 },
      { serviceId: "srv-6", quantidade: 1, valorUnitario: 4500.0 },
      { serviceId: "srv-1", quantidade: 1, valorUnitario: 540.0 },
    ],
    funcionariosIds: ["emp-2", "emp-4", "emp-5"],
    assinaturaNome: "Juliana Frota Marques",
    assinaturaData: "2026-03-15T09:40:00.000Z",
    anexos: [
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=600&q=80"
    ],
    valorTotal: 8540.0,
    createdAt: "2026-03-15T09:30:00.000Z",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    tipo: "receita",
    categoria: "Eventos",
    descricao: "Entrada (50%) OS-2026-0001 - Carlos Silva",
    valor: 2620.0,
    data: "2026-01-20",
    osId: "os-1",
    status: "pago",
  },
  {
    id: "tx-2",
    tipo: "receita",
    categoria: "Eventos",
    descricao: "Faturamento Integral OS-2026-0004 - Juliana Frota",
    valor: 8540.0,
    data: "2026-03-15",
    osId: "os-4",
    status: "pago",
  },
  {
    id: "tx-3",
    tipo: "despesa",
    categoria: "Folha de Pagamento",
    descricao: "Diária DJ Daniel Souza (OS-2026-0004)",
    valor: 400.0,
    data: "2026-05-10",
    osId: "os-4",
    status: "pago",
  },
  {
    id: "tx-4",
    tipo: "despesa",
    categoria: "Folha de Pagamento",
    descricao: "Diária Decoradora Ana Carolina (OS-2026-0004)",
    valor: 350.0,
    data: "2026-05-10",
    osId: "os-4",
    status: "pago",
  },
  {
    id: "tx-5",
    tipo: "despesa",
    categoria: "Insumos & Bebidas",
    descricao: "Compra de destilados e frutas para coquetéis",
    valor: 850.0,
    data: "2026-04-05",
    status: "pago",
  },
  {
    id: "tx-6",
    tipo: "despesa",
    categoria: "Infraestrutura",
    descricao: "Aluguel de gerador de energia reserva",
    valor: 1200.0,
    data: "2026-04-18",
    status: "pago",
  },
  {
    id: "tx-7",
    tipo: "receita",
    categoria: "Patrocínio / Parceria",
    descricao: "Bônus de indicação - Fornecedor de Tendras",
    valor: 300.0,
    data: "2026-04-20",
    status: "pago",
  },
  {
    id: "tx-8",
    tipo: "despesa",
    categoria: "Marketing",
    descricao: "Tráfego pago Instagram/Google Ads",
    valor: 600.0,
    data: "2026-05-01",
    status: "pago",
  },
];
