CREATE TABLE Users (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  Name NVARCHAR(160) NOT NULL,
  Email NVARCHAR(180) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  Role NVARCHAR(30) NOT NULL DEFAULT 'OPERADOR',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Clients (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  Nome NVARCHAR(180) NOT NULL,
  Email NVARCHAR(180) NULL,
  Telefone NVARCHAR(40) NULL,
  Documento NVARCHAR(40) NULL,
  Endereco NVARCHAR(260) NULL,
  Observacoes NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE INDEX IX_Clients_Nome ON Clients (Nome);

CREATE TABLE Employees (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  Nome NVARCHAR(180) NOT NULL,
  Cargo NVARCHAR(120) NOT NULL,
  Telefone NVARCHAR(40) NULL,
  ValorDiaria DECIMAL(10, 2) NOT NULL DEFAULT 0,
  TipoPagamento NVARCHAR(30) NOT NULL DEFAULT 'diaria',
  Observacoes NVARCHAR(MAX) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Services (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  Nome NVARCHAR(180) NOT NULL,
  Descricao NVARCHAR(MAX) NULL,
  Valor DECIMAL(10, 2) NOT NULL DEFAULT 0,
  DuracaoHoras DECIMAL(5, 2) NOT NULL DEFAULT 0,
  Categoria NVARCHAR(120) NOT NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'ativo'
);

CREATE TABLE ServiceOrders (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  Codigo NVARCHAR(40) NOT NULL UNIQUE,
  ClienteId UNIQUEIDENTIFIER NOT NULL,
  DataEvento DATE NOT NULL,
  HorarioInicio NVARCHAR(10) NOT NULL,
  HorarioFim NVARCHAR(10) NOT NULL,
  Local NVARCHAR(300) NOT NULL,
  Status NVARCHAR(40) NOT NULL DEFAULT 'PENDENTE',
  FormaPagamento NVARCHAR(160) NULL,
  Observacoes NVARCHAR(MAX) NULL,
  AssinaturaNome NVARCHAR(180) NULL,
  AssinaturaData DATETIME2 NULL,
  Anexos NVARCHAR(MAX) NULL,
  ValorTotal DECIMAL(10, 2) NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_ServiceOrders_Clients FOREIGN KEY (ClienteId) REFERENCES Clients(Id)
);

CREATE INDEX IX_ServiceOrders_DataEvento ON ServiceOrders (DataEvento);
CREATE INDEX IX_ServiceOrders_Status ON ServiceOrders (Status);

CREATE TABLE ServiceOrderItems (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  OrderId UNIQUEIDENTIFIER NOT NULL,
  ServiceId UNIQUEIDENTIFIER NOT NULL,
  Quantidade INT NOT NULL DEFAULT 1,
  ValorUnitario DECIMAL(10, 2) NOT NULL DEFAULT 0,
  CONSTRAINT FK_ServiceOrderItems_Orders FOREIGN KEY (OrderId) REFERENCES ServiceOrders(Id) ON DELETE CASCADE,
  CONSTRAINT FK_ServiceOrderItems_Services FOREIGN KEY (ServiceId) REFERENCES Services(Id)
);

CREATE TABLE ServiceOrderEmployees (
  OrderId UNIQUEIDENTIFIER NOT NULL,
  EmployeeId UNIQUEIDENTIFIER NOT NULL,
  PRIMARY KEY (OrderId, EmployeeId),
  CONSTRAINT FK_ServiceOrderEmployees_Orders FOREIGN KEY (OrderId) REFERENCES ServiceOrders(Id) ON DELETE CASCADE,
  CONSTRAINT FK_ServiceOrderEmployees_Employees FOREIGN KEY (EmployeeId) REFERENCES Employees(Id)
);

CREATE TABLE Transactions (
  Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  Tipo NVARCHAR(30) NOT NULL,
  Categoria NVARCHAR(120) NOT NULL,
  Descricao NVARCHAR(260) NOT NULL,
  Valor DECIMAL(10, 2) NOT NULL,
  Data DATE NOT NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'pendente',
  OsId UNIQUEIDENTIFIER NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Transactions_ServiceOrders FOREIGN KEY (OsId) REFERENCES ServiceOrders(Id) ON DELETE SET NULL
);

CREATE INDEX IX_Transactions_Data ON Transactions (Data);
CREATE INDEX IX_Transactions_Tipo ON Transactions (Tipo);